### ISSUE TITLE
Cell model questions

### ISSUE THREAD

**Issue by andrisecker** [mbezaire/ca1#5]
Just a quick question:
Do you want to insert non-uniform channel densities for CCK, Ivy, NGF and SCA cells with the code snippet below or just check if the distance is lower then 100 um?

```
for(x,0) {
    if (distance(x)<100) {
        ...
        gmax_ch_Navcck = gNav*.5  // original code
        //gmax_ch_Navcck(x) = gNav*.5  // should be for non-uniform chan. densities - Andras
```

CCK cell: https://github.com/mbezaire/ca1/blob/master/cells/class_cckcell.hoc#292
Ivy cell: https://github.com/mbezaire/ca1/blob/master/cells/class_ivycell.hoc#L311
NGF cell: https://github.com/mbezaire/ca1/blob/master/cells/class_ngfcell.hoc#L311
SCA cell: https://github.com/mbezaire/ca1/blob/master/cells/class_scacell.hoc#290

**Comment by andrisecker** [comment]
sorry I missed the comment in the code...
the problem isn't uniform vs. non-uniform but inserting into the given section (below 100um) or inserting only into the segments within the section, whose are below 100um 

`
        //gmax_ch_Navcck(x) = gNav*.5  // inserts to given segment, not the whole section!
`

1 more question about these 4 cells:
In CCK and SCA eca is set to ecaval (and kept constant), while in Ivy and NGF ecaval is calculated, but not used, thus NEURON keeps updating eca. Was this the purpose or is it a bug?
(eca is used by ch_CavN)

**Comment by mbezaire** [comment]
Closing out this issue and copying the text from Andras' most recent comment into the other open issue about calcium calculations
